services:

  shipment-service:
    build: ./backend/shipment-service
    container_name: shipment-service
    ports:
      - "8000:8000"
    env_file:
      - ./backend/shipment-service/.env
    restart: always

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    env_file:
      - ./backend/auth-service/.env
    restart: always

  fleet-service:
    build: ./backend/fleet-service
    container_name: fleet-service
    ports:
      - "8002:8002"
    env_file:
      - ./backend/fleet-service/.env
    restart: always

  telemetry-service:
    build: ./backend/telemetry-service
    container_name: telemetry-service
    ports:
      - "8004:8004"
    env_file:
      - ./backend/telemetry-service/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - shipment-service
      - fleet-service
      - telemetry-service
    restart: always